### ISSUE TITLE
 Not working as of Atom 1.33.1

### ISSUE THREAD

**Issue by ghost** [wfpaisa/plane-atom-ui#1]
I downloaded and extracted the theme folder to ~/.atom/packages and I restarted atom and selected it. Nothing changed and the selection reverted back to what it was before.

Same issue with the syntax theme.

**Comment by wfpaisa** [comment]
Hi cether, you are right, I think is the folder name, please:

1. Download in `~/.atom/packages/plane-atom-ui` - and (window:reload)
2. Open: Settings -> Themes -> UI theme  and choose: Plane Atom
3. I recommending install too, install [plane-atom-syntax](https://github.com/wfpaisa/plane-atom-syntax)

**Comment by ghost** [comment]
You're correct, the file name was the issue. I did as you instructed - I took the same folders, renamed them to just say `plane-atom-<ui/syntax>` and they worked. Thanks a bunch! Your work is gorgeous.
